[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["mypackage1"]

[project]
name = "lablib102"
version = "0.2.7"
description = "personal library for my lab"
authors = [{ name = "haiteng" }]
dependencies = []
