[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lablib"
version = "0.2.0"
description = "personal library for my lab"
authors = [{ name = "haiteng" }]
dependencies = []
